name: Flutter Android CI

on:
  push:
    branches:
      - main  # 或其他你希望监控的分支
  pull_request:
    branches:
      - main  # 或其他你希望监控的分支

jobs:
  build:

    runs-on: ubuntu-latest  # 使用 macOS 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'  # 替换为你希望使用的 Flutter 版本

      - name: set up jdk17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android
        run: |
          flutter build apk -v


      - name: Upload APK
        uses: actions/upload-artifact@v3  # 更新为新版本
        with:
          name: MyApp.apk
          path: /build/app/outputs/apk/release/*.apk