name: Flutter iOS CI

on:
  push:
    branches:
      - main  # 或其他你希望监控的分支
  pull_request:
    branches:
      - main  # 或其他你希望监控的分支

jobs:
  build:

    runs-on: macos-latest  # 使用 macOS 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'  # 替换为你希望使用的 Flutter 版本

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: |
          cd ios
          pod install  # 确保 CocoaPods 安装依赖
          cd ..
          flutter build ios --release --no-codesign --obfuscate --split-debug-info=./symbols

      # - name: Build IPA
      #   run: |
      #     cd ios
      #     xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -archivePath build/Runner.xcarchive CODE_SIGNING_ALLOWED=NO archive
      #     xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath build

      - name: ls
        run: |
          cd build/ios/iphoneos/Runner.app/Frameworks
          cd App.framework
          xcrun bitcode_strip -r app -o app
          cd ..
          cd Flutter.framework
          xcrun bitcode_strip -r Flutter -o Flutter
          cd ..
          xcrun bitcode_strip -r libswiftCore.dylib -o libswiftCore.dylib  
          xcrun bitcode_strip -r libswiftFoundation.dylib -o libswiftFoundation.dylib
          xcrun bitcode_strip -r libswiftDispatch.dylib -o libswiftDispatch.dylib
          cd Flutter.framework

          cd ../../../
          rm -rf Payload
          mkdir Payload
          mv Runner.app Payload/Runner.app
          zip -9 -r app.zip Payload
          rm -rf app.ipa
          mv app.zip app.ipa


      - name: Upload IPA
        uses: actions/upload-artifact@v3  # 更新为新版本
        with:
          name: MyApp.ipa
          path: build/ios/iphoneos/*.ipa