name: Flutter iOS CI

on:
  push:
    branches:
      - main  # 或其他你希望监控的分支
  pull_request:
    branches:
      - main  # 或其他你希望监控的分支

jobs:
  build:

    runs-on: macos-latest  # 使用 macOS 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'  # 替换为你希望使用的 Flutter 版本

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: |
          cd ios
          pod install  # 确保 CocoaPods 安装依赖
          cd ..
          flutter build ios --release  # 构建 iOS 应用